export const resourceArticleStyles = {
  page: 'min-h-screen bg-gray-50',
  container: 'max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8',
  wideContainer: 'max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8',
  heroCard: 'mb-8 max-w-full overflow-hidden rounded-xl bg-white text-gray-900 shadow-lg',
  heroInner: 'min-w-0 px-5 py-10 sm:px-8 sm:py-12',
  contentCard: 'max-w-none overflow-hidden rounded-xl bg-white p-5 text-gray-900 shadow-lg sm:p-8',
  proseCard: 'prose prose-lg max-w-none overflow-hidden rounded-xl bg-white p-5 text-gray-900 shadow-lg sm:p-8',
  tocCard: 'w-full max-w-full overflow-hidden rounded-lg border border-gray-200 bg-white p-4 text-gray-900 shadow',
  tocList: 'space-y-2 text-sm min-w-0',
  tocNestedList: 'mt-1 space-y-1 border-l border-gray-200 pl-3',
  tocLink: 'block break-words text-blue-600 transition-colors hover:text-blue-800 hover:underline',
  tocSubLink: 'block break-words text-xs text-gray-600 transition-colors hover:text-blue-600 hover:underline',
  summaryCard: 'rounded-lg border border-gray-200 bg-gray-50 p-5 text-gray-900 sm:p-6',
  summaryList: 'space-y-4 min-w-0',
  summaryItem: 'flex min-w-0 items-start gap-3',
  tableWrap: 'overflow-x-auto mb-8',
  table: 'w-full border-collapse border border-gray-300 text-gray-900',
  tableBody: 'text-gray-700',
} as const;
